
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
admin=animelord.models.AdminDashboardModel
anime=animelord.models.AnimeListModel
index=animelord.models.HomePageModel
home=animelord.models.HomePageModel
login=/WEB-INF/views/login.jsp
register=/WEB-INF/views/register.jsp
doLogin=animelord.models.LoginModel
doRegister=animelord.models.RegisterModel
verify=animelord.models.VerifyAccountModel
logout=animelord.models.LogoutModel
saveAnime=animelord.models.AddAnimeModel
saveEpisode=animelord.models.UploadEpisodeModel
updateAnime=animelord.models.UpdateAnimeModel
deleteAnime=animelord.models.DeleteAnimeModel
deleteEpisode=animelord.models.DeleteEpisodeModel
updateEpisode=animelord.models.UpdateEpisodeModel
encodingQueue=animelord.models.EncodingQueueModel
startEncoding=animelord.models.StartEncodingModel
searchAnimeAjax=animelord.models.SearchAnimeAjaxModel
animeDetails=animelord.models.AnimeDetailsModel