
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
admin=animelord.models.AdminDashboardModel
index=animelord.models.HomePageModel
home=animelord.models.HomePageModel
login=/WEB-INF/views/login.jsp
register=/WEB-INF/views/register.jsp
doLogin=animelord.models.LoginModel
doRegister=animelord.models.RegisterModel
verify=animelord.models.VerifyAccountModel
logout=animelord.models.LogoutModel
saveAnime=animelord.models.AddAnimeModel
updateAnime=animelord.models.UpdateAnimeModel